PKGDIR ?= ../..
L4DIR  ?= $(PKGDIR)/../..

TARGET = $(PKGNAME)

SRC_CC = fb_log.cc fb_log_server.cc fb_log_session_server.cc fb_textbox.cc

REQUIRES_LIBS = libc_be_mem libstdc++ libgfxbitmap

include $(L4DIR)/mk/prog.mk
