PKGDIR ?= ../..
L4DIR  ?= $(PKGDIR)/../..

TARGET = $(PKGNAME)

SRC_CC = keyboard_drv.cc keyboard_server.cc keyboard_session_server.cc

REQUIRES_LIBS = libc_be_mem libio libpthread libstdc++

include $(L4DIR)/mk/prog.mk
